- name: Test connection to FortiGate API
  hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  tasks:
    - name: Get system interface info
      fortios_system_interface:
        state: present
        system_interface:
          name: "port1"
