- name: Test connection to FortiGate API
  hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  gather_facts: no
  tasks:
    - name: Get system interface info
      fortios_system_interface:
        state: present
        system_interface:
          name: port1
